version: "2"
services:
  vizque_apps:
    image: vizque_img
    container_name: vizque
    build: .
    volumes:
      - ./vizque:/VizQue/vizque
      - ./react-app:/VizQue/react-app
    ports:
      - "5555:5555"
    tty: true
    stdin_open: true
    privileged: true
