version: "3"
services:
  nimslogic:
    image: nim/1.4.4
    container_name: nim
    build: ./Docker/Nim
    volumes:
      - ./server:/prj/server
    tty: true
    stdin_open: true
    privileged: true

  restapi:
    image: python/3.8.8
    container_name: fastapi
    build: ./Docker/Python
    volumes:
      - ./server:/prj/server
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - "8353:8353"

  front:
    image: reactapp
    container_name: graphdisplay
    build: ./Docker/NodeJS
    volumes:
      - ./front:/prj/front
    tty: true
    stdin_open: true
    ports:
      - "5555:5555"
